CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date VARCHAR(20) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  item VARCHAR(40) NOT NULL,
  category VARCHAR(40) NOT NULL
);
